import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]


[window]
  opacity= 0.8666666666666
  padding = {x = 0, y = 0}
  decorations = "None"
  resize_increments = true

[font]
size = 12.0

[font.bold]
family = "Terminess Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

